---
title: "index.qmd"
format: html
editor: Miguel Villa and Drew Ambrogi
---

## Opening Dataset
From the Tidy Tuesday Series: Energy, Our World in Data. 
```{r}
# Opening Dataset
install.packages("tidytuesdayR")
owid_energy <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2023/2023-06-06/owid-energy.csv')

```

## Visualization 1

```{r}
library(tidyverse)
library(ggplot2)
library(scales)

#Preparing data
vis01 <- owid_energy %>%
  filter(year == 2018, country != "World") %>%    
  filter(!is.na(gdp), !is.na(population), !is.na(renewables_share_energy)) %>% 
  mutate(
    gdp_per_capita = gdp / population             
  )

#Creating plot
ggplot(vis01, aes(
  x = gdp_per_capita, 
  y = renewables_share_energy, 
  size = population,
  color = renewables_share_energy
  )) +
geom_point(alpha = 0.7) +
geom_text_repel(
  data = filter(vis01, country == "United States"),
  aes(label = country),
  color = "black",
  size = 3.5,
  nudge_y = 5,
  nudge_x = 0.3, 
  segment.color = "gray60",
  segment.size = 0.3
)+
scale_x_log10(labels = label_dollar()) +
scale_y_continuous(labels = label_percent(scale = 1, accuracy = 1)) +
scale_color_gradient(
  low = "red", 
  high = "darkgreen",
  labels = label_percent(scale = 1,),
  name = "Renewables share"
)+
scale_size_continuous(
  name = "Population",
  labels = label_number(big.mark = ",", accuracy = 1)
)+
labs(
  title = "Renewable Energy vs. GDP per Capita (2018)",
  subtitle = "Each point represents a country",
  caption = "Source: Our World in Data, Energy Data Explorer, via TidyTuesday",
  x = "GDP per Capita (USD)",
  y = "Share of primary energy from renewables"
)
```
  
## Visualization 2

```{r}
# Preparing Data
us <- owid_energy |>
  filter(country == "United States") |>
  pivot_longer(
    cols = c(gas_share_energy,
             hydro_share_energy,
             nuclear_share_energy,
             coal_share_energy,
             oil_share_energy),
    names_to = "energy_source",
    values_to = "share") |>
  drop_na() 

# Creating Plot
us |>
  ggplot(aes(x = year, y = share, color = energy_source)) +
  geom_smooth(linewidth = 1) +
  geom_point() +
  scale_color_manual(
    values = c(
      coal_share_energy = "red",   
      gas_share_energy = "darkorange",
      oil_share_energy = "brown",
      hydro_share_energy = "lightblue", 
      nuclear_share_energy = "blue"
    ),
    labels = c(
      coal_share_energy = "Coal",
      gas_share_energy = "Gas",
      oil_share_energy = "Oil",
      hydro_share_energy = "Hydro",
      nuclear_share_energy = "Nuclear"
    ),
    name = "Energy Source"
  ) +
  labs(
    title = "Trends in U.S. Energy Production by Source (2000–2018)",
    subtitle = "Share of total energy production by source over time",
    x = "Year",
    y = "Share of Total U.S. Energy Production",
    caption = "Source: Our World in Data, Energy Data Explorer, via TidyTuesday") +
  theme_minimal() 
```
  
## Visualization 3

```{r}
# Preparing Data 
a <- owid_energy |>
  filter(country %in% c("Low-income countries",
                        "Lower-middle-income countries",
                        "Upper-middle-income countries",
                        "High-income countries")) |>
  pivot_longer(
    cols = c(gas_share_energy,
             hydro_share_energy,
             nuclear_share_energy,
             coal_share_energy,
             oil_share_energy),
    names_to = "energy_source",
    values_to = "share"
  ) |>
  filter(!is.na(population), !is.na(share)) |>
  filter(year == 2018) |>
  mutate(country = recode(country,
                          "High-income countries" = "High",
                          "Upper-middle-income countries" = "Upper-Middle",
                          "Lower-middle-income countries" = "Lower-Middle")) |>
  rename(
    `Countries` = country,
    `Energy Source` = energy_source) 

# Creating Plot
ggplot(a, aes(x = `Countries`, y = share, fill = `Countries`)) +
  geom_col(width = 0.4) +
  geom_text(aes(label = paste0(round(share, 0), "%")),
            vjust = 0,
            size = 2.5) +    
  facet_wrap(~ `Energy Source`, labeller = labeller(
    `Energy Source` = c(
      coal_share_energy = "Coal",
      gas_share_energy = "Gas",
      hydro_share_energy = "Hydro",
      nuclear_share_energy = "Nuclear",
      oil_share_energy = "Oil"),
    ncol = 1, scales = "fixed")) +
  labs(
    title = "Energy Source Share for Different Income Countries",
    subtitle = "Lower-Middle, Upper-Middle, and High Income Countries",
    x = "Energy Source",
    y = "Share of Energy (%)",
    color = "Income Group",
    caption = "Source: Our World in Data, Energy Data Explorer, via TidyTuesday"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    strip.text = element_text(face = "bold", size = 11),
    plot.title = element_text(face = "bold", size = 14, hjust = 0.5),
    plot.subtitle = element_text(size = 11, hjust = 0.5),
    legend.position = "bottom"
  )
```
  